import type { ColDef } from "ag-grid-community";

/** HR9200 在产物料跟踪 —— 列定义（按提取摘要 temp/mig/HR9200.txt 逐表核对 swagger 实体字段生成，隐藏列 hide:true 收着） */

export const mainColDefs: ColDef[] = [
  { field: "selected", headerName: "选择", width: 150 },
  { field: "createTime", headerName: "创建时间", width: 150 },
  { field: "creator", headerName: "创建人", width: 150 },
  { field: "cPos", headerName: "当前位置", width: 150 },
  { field: "cBatchNo", headerName: "批号", width: 150 },
  { field: "cStove", headerName: "炉号", width: 150 },
  { field: "cBatchOrder", headerName: "组批号", width: 150 },
  { field: "cOrderNo", headerName: "提料计划号", width: 150 },
  { field: "cPieceNo", headerName: "熔炼序号", width: 150 },
  { field: "cPrintCode", headerName: "喷印号", width: 150 },
  { field: "cSgCode", headerName: "冶炼钢种", width: 150 },
  { field: "nThick", headerName: "坯厚", width: 150 },
  { field: "nWidth", headerName: "坯宽", width: 150 },
  { field: "nLen", headerName: "坯长", width: 150 },
  { field: "nWgt", headerName: "重量", width: 150 },
  { field: "nThickPlan", headerName: "计划厚度", width: 150 },
  { field: "nWidthPlan", headerName: "计划宽度", width: 150 },
  { field: "nLenPlan", headerName: "计划长度", width: 150 },
  { field: "cSgCodePlan", headerName: "计划钢种", width: 150 },
  { field: "cSgStdPlan", headerName: "计划执行标准", width: 150 },
  { field: "nRateLl", headerName: "理论成材率", width: 150 },
  { field: "cTol", headerName: "公差", width: 150 },
  { field: "cDn", headerName: "需要堆冷", width: 150 },
  { field: "cTrimFlag", headerName: "切边方式", width: 150 },
  { field: "cFlawDesc", headerName: "探伤等级", width: 150 },
  { field: "cSpecialMarkGy", headerName: "性能要求", width: 150 },
  { field: "cDelivyAddress", headerName: "流向", width: 150 },
  { field: "cOrderNo1", headerName: "订单号1", width: 150 },
  { field: "cOrderNo2", headerName: "订单号2", width: 150 },
  { field: "cOrderNo3", headerName: "订单号3", width: 150 },
  { field: "cOrderNo4", headerName: "订单号4", width: 150 },
  { field: "nLenTq1", headerName: "套切1", width: 150 },
  { field: "nLenTq2", headerName: "套切2", width: 150 },
  { field: "nLenTq3", headerName: "套切3", width: 150 },
  { field: "nLenTq4", headerName: "套切4", width: 150 },
  { field: "nBc", headerName: "倍尺", width: 150 },
  { field: "cBilletTypeCode", headerName: "铸坯标识", width: 150 },
  { field: "cProRemark", headerName: "生产备注", width: 150 },
  { field: "id", headerName: "主键", width: 150, hide: true },
  { field: "dRl", headerName: "入炉时间", width: 150, hide: true },
  { field: "cOrderId", headerName: "THR2000主键", width: 150, hide: true },
  { field: "cZpId", headerName: "THR3000主键", width: 150, hide: true },
  { field: "cSlabId", headerName: "TYD2000主键", width: 150, hide: true },
  { field: "cLineCode", headerName: "产线代码", width: 150, hide: true },
  { field: "cRowNo", headerName: "道次", width: 150, hide: true },
  { field: "nQua", headerName: "支数", width: 150, hide: true },
  { field: "nWgtCz", headerName: "称重重量", width: 150, hide: true },
  { field: "cInboundNo1", headerName: "入库标识1", width: 150, hide: true },
  { field: "cInboundNo2", headerName: "入库标识2", width: 150, hide: true },
  { field: "cInboundNo3", headerName: "入库标识3", width: 150, hide: true },
  { field: "cInboundNo4", headerName: "入库标识4", width: 150, hide: true },
  { field: "cFurCode", headerName: "加热炉编号", width: 150, hide: true },
  { field: "nFurStatus", headerName: "加热炉状态", width: 150, hide: true },
  { field: "cPlateNo", headerName: "钢板号", width: 150, hide: true },
  { field: "cSpecPlan", headerName: "计划规格", width: 150, hide: true },
  { field: "nOrderPlan", headerName: "计划生产顺序", width: 150, hide: true },
  { field: "nOrder", headerName: "生产顺序号", width: 150, hide: true },
  { field: "nL2Status", headerName: "L2计划状态", width: 150, hide: true },
  { field: "cSgStd", headerName: "执行标准", width: 150, hide: true },
  { field: "cSpec", headerName: "规格", width: 150, hide: true },
];

export interface TabGridDef {
  title: string;
  colDefs: ColDef[];
}

export const tabGridDefs: TabGridDef[] = [
  /* 上辊道实绩（gridControl4 / TiL2me04） */
  {
    title: "上辊道实绩",
    colDefs: [
      { field: "createTime", headerName: "创建时间", width: 150 },
      { field: "plateNo", headerName: "钢板号", width: 150 },
      { field: "slabNo", headerName: "板坯号", width: 150 },
      { field: "tableNo", headerName: "辊道号", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 照核记录（gridControl3 / TiL2ME05ItemDto） */
  {
    title: "照核记录",
    colDefs: [
      { field: "createTime", headerName: "创建时间", width: 150 },
      { field: "slabNo", headerName: "板坯号", width: 150 },
      { field: "printCode", headerName: "喷印号", width: 150 },
      { field: "mesCallBack", headerName: "MES反馈", width: 150 },
      { field: "l2CallBack", headerName: "L2反馈", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
      { field: "cStove", headerName: "炉号", width: 150, hide: true },
      { field: "cPieceNo", headerName: "头侧件次号", width: 150, hide: true },
      { field: "nProType", headerName: "库存类型", width: 150, hide: true },
      { field: "cPrintCode", headerName: "喷号", width: 150, hide: true },
      { field: "cLineCode", headerName: "产线", width: 150, hide: true },
      { field: "cProc", headerName: "工序", width: 150, hide: true },
      { field: "cMachine", headerName: "炉台号", width: 150, hide: true },
      { field: "cStrandNo", headerName: "流号", width: 150, hide: true },
      { field: "cPlanId", headerName: "计划ID", width: 150, hide: true },
      { field: "cConNo", headerName: "合同号", width: 150, hide: true },
      { field: "cOrderNo", headerName: "订单号", width: 150, hide: true },
      { field: "cMatCode", headerName: "物料编码", width: 150, hide: true },
      { field: "cSgCode", headerName: "钢种", width: 150, hide: true },
      { field: "cSgStd", headerName: "执行标准", width: 150, hide: true },
      { field: "nThick", headerName: "坯厚", width: 150, hide: true },
      { field: "nWth", headerName: "宽度", width: 150, hide: true },
      { field: "nLen", headerName: "坯长", width: 150, hide: true },
      { field: "cSpec", headerName: "规格", width: 150, hide: true },
      { field: "nNum", headerName: "提货件数", width: 150, hide: true },
      { field: "nCalWgt", headerName: "理重", width: 150, hide: true },
      { field: "nWgt", headerName: "坯重", width: 150, hide: true },
      { field: "dProTime", headerName: "产出时间", width: 150, hide: true },
      { field: "cProUser", headerName: "产出人", width: 150, hide: true },
      { field: "cShiftNo", headerName: "结果录入班次", width: 150, hide: true },
      { field: "cGroupNo", headerName: "结果录入班组", width: 150, hide: true },
      { field: "dInTime", headerName: "入库时间", width: 150, hide: true },
      { field: "cInUser", headerName: "入库人", width: 150, hide: true },
      { field: "cStoreCode", headerName: "库区号", width: 150, hide: true },
      { field: "cStackNo", headerName: "垛位号", width: 150, hide: true },
      { field: "cStackNum", headerName: "层号", width: 150, hide: true },
      { field: "cSourceStoreCode", headerName: "原库区号", width: 150, hide: true },
      { field: "cSourceStackNo", headerName: "原垛位号", width: 150, hide: true },
      { field: "cSourceStackNum", headerName: "原层号", width: 150, hide: true },
      { field: "nStatus", headerName: "处理标记", width: 150, hide: true },
      { field: "cIsHot", headerName: "是否热送", width: 150, hide: true },
      { field: "cProRemark", headerName: "生产备注", width: 150, hide: true },
      { field: "nCastDivCode", headerName: "模连铸标识", width: 150, hide: true },
      { field: "cLockedLine", headerName: "占用产线", width: 150, hide: true },
      { field: "cLockedPlan", headerName: "占用计划", width: 150, hide: true },
      { field: "cMatType", headerName: "类型(销售坯)", width: 150, hide: true },
      { field: "cProdCode", headerName: "品名", width: 150, hide: true },
      { field: "cSteelType", headerName: "钢种大类", width: 150, hide: true },
      { field: "cDelivyStatusCode", headerName: "交货状态", width: 150, hide: true },
      { field: "cCustStdCode", headerName: "加工用途代码", width: 150, hide: true },
      { field: "cBatchNo", headerName: "批号", width: 150, hide: true },
      { field: "cOrderNoLast", headerName: "原始订单号", width: 150, hide: true },
      { field: "cDestination", headerName: "去向", width: 150, hide: true },
      { field: "cHotNo", headerName: "退火炉回号", width: 150, hide: true },
      { field: "cSlabType", headerName: "自备坯R", width: 150, hide: true },
      { field: "cPieceNoSlab", headerName: "板坯号", width: 150, hide: true },
      { field: "nQmStatus", headerName: "质量状态", width: 150, hide: true },
      { field: "nLockReason", headerName: "质量封锁原因", width: 150, hide: true },
      { field: "nQmLevel", headerName: "质量等级", width: 150, hide: true },
      { field: "cIsSurface", headerName: "是否表检", width: 150, hide: true },
      { field: "cSurfaceResult", headerName: "表检结果", width: 150, hide: true },
      { field: "cSurfaceDefectCode", headerName: "表面缺陷代码", width: 150, hide: true },
      { field: "cSurfaceDesc", headerName: "表检描述", width: 150, hide: true },
      { field: "cSurfaceUser", headerName: "表面判定人", width: 150, hide: true },
      { field: "dSurfaceTime", headerName: "表面判定时间", width: 150, hide: true },
      { field: "cDetectResultCode", headerName: "探伤判定结果", width: 150, hide: true },
      { field: "cDetectDefectLevel", headerName: "探伤等级", width: 150, hide: true },
      { field: "cDefectDefectCode", headerName: "探伤判定缺陷代码", width: 150, hide: true },
      { field: "cDefectDefectMark", headerName: "探伤判定缺陷描述", width: 150, hide: true },
      { field: "cDefectUser", headerName: "探伤判定人", width: 150, hide: true },
      { field: "dDefectTime", headerName: "探伤判定时间", width: 150, hide: true },
      { field: "cComplexDecideCode", headerName: "综判结果", width: 150, hide: true },
      { field: "cComplexDesc", headerName: "综判描述", width: 150, hide: true },
      { field: "cComplexUser", headerName: "综判人", width: 150, hide: true },
      { field: "dComplexTime", headerName: "综判时间", width: 150, hide: true },
      { field: "cQmHandleCode", headerName: "处置结果", width: 150, hide: true },
      { field: "cQmHandleDesc", headerName: "处置注释", width: 150, hide: true },
      { field: "cQmHandleUser", headerName: "处置人", width: 150, hide: true },
      { field: "dQmHandleTime", headerName: "处置时间", width: 150, hide: true },
      { field: "cSampleLotNo", headerName: "试批号", width: 150, hide: true },
      { field: "cSampleLotNoPre", headerName: "前检验委托单号", width: 150, hide: true },
      { field: "cCutFlag", headerName: "切边方式", width: 150, hide: true },
      { field: "cInboundNo", headerName: "入库标识", width: 150, hide: true },
      { field: "cDelivyAddress", headerName: "流向", width: 150, hide: true },
      { field: "cWgtToler", headerName: "重量偏差等级", width: 150, hide: true },
      { field: "cBilletTypeCode", headerName: "铸坯标识", width: 150, hide: true },
      { field: "cCusName", headerName: "客户名称", width: 150, hide: true },
      { field: "pLAN_CSpec", headerName: "剪切计划规格", width: 150, hide: true },
      { field: "pLAN_NThickPlan", headerName: "轧制厚", width: 150, hide: true },
      { field: "pLAN_NWidthPlan", headerName: "轧制宽", width: 150, hide: true },
      { field: "pLAN_NLlCleanLen", headerName: "轧制长", width: 150, hide: true },
      { field: "pLAN_COrderNo1", headerName: "订单号1", width: 150, hide: true },
      { field: "pLAN_COrderNo2", headerName: "订单号2", width: 150, hide: true },
      { field: "pLAN_COrderNo3", headerName: "订单号3", width: 150, hide: true },
      { field: "pLAN_COrderNo4", headerName: "订单号4", width: 150, hide: true },
      { field: "pLAN_COrderNo5", headerName: "订单号5", width: 150, hide: true },
      { field: "pLAN_COrderNo6", headerName: "订单号6", width: 150, hide: true },
      { field: "pLAN_NLenPlan1", headerName: "套切长度1", width: 150, hide: true },
      { field: "pLAN_NLenPlan2", headerName: "套切长度2", width: 150, hide: true },
      { field: "pLAN_NLenPlan3", headerName: "套切长度3", width: 150, hide: true },
      { field: "pLAN_NLenPlan4", headerName: "套切长度4", width: 150, hide: true },
      { field: "pLAN_NLenPlan5", headerName: "套切长度5", width: 150, hide: true },
      { field: "pLAN_NLenPlan6", headerName: "套切长度6", width: 150, hide: true },
      { field: "nKSgCode", headerName: "国标钢种", width: 150, hide: true },
    ],
  },
  /* 装炉实绩（gridControl5 / TiL2me06） */
  {
    title: "装炉实绩",
    colDefs: [
      { field: "createTime", headerName: "创建时间", width: 150 },
      { field: "slabNo", headerName: "板坯号", width: 150 },
      { field: "furNo", headerName: "炉号", width: 150 },
      { field: "rowNo", headerName: "列号", width: 150 },
      { field: "spare1", headerName: "预留", width: 150 },
      { field: "spare2", headerName: "预留（照核长度）", width: 150 },
      { field: "spare3", headerName: "预留（炉前称重）", width: 150 },
      { field: "spare4", headerName: "照核长度", width: 150 },
      { field: "spare5", headerName: "照核宽度", width: 150 },
      { field: "spare6", headerName: "照核厚度", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 加热实绩（gridControl6 / TiL2me11） */
  {
    title: "加热实绩",
    colDefs: [
      { field: "createTime", headerName: "创建时间", width: 150 },
      { field: "matNo", headerName: "材料号", width: 150 },
      { field: "planNo", headerName: "计划号", width: 150 },
      { field: "slabFurTime", headerName: "板坯装炉时刻", width: 150 },
      { field: "slabFurBefTemp", headerName: "板坯装炉前温度", width: 150 },
      { field: "furNo", headerName: "加热炉号", width: 150 },
      { field: "furType", headerName: "加热炉类型", width: 150 },
      { field: "inFurnaceShiftNo", headerName: "入炉班次", width: 150 },
      { field: "inFurnaceShiftGroup", headerName: "入炉班组", width: 150 },
      { field: "outFurnaceShiftNo", headerName: "出炉班次", width: 150 },
      { field: "outFurnaceShiftGroup", headerName: "出炉班组", width: 150 },
      { field: "tapSlabTempAve", headerName: "出钢时板坯平均温度", width: 150 },
      { field: "tapSlabTempSrfc", headerName: "出钢时板坯表面温度", width: 150 },
      { field: "tapSlabTempCt", headerName: "出钢时板坯中心温度", width: 150 },
      { field: "outTime", headerName: "抽出时刻", width: 150 },
      { field: "outTempAvg", headerName: "抽出平均温度", width: 150 },
      { field: "inFurnaceTime", headerName: "在炉内时间", width: 150 },
      { field: "preHtTempAve", headerName: "预热段入口的平均板坯温度", width: 150 },
      { field: "preHtHotAve", headerName: "预热段入口的板坯均热温度", width: 150 },
      { field: "preHtTempSrf", headerName: "预热段入口的板坯表面温度", width: 150 },
      { field: "preHtTempCt", headerName: "预热段入口的板坯中心温度", width: 150 },
      { field: "preHtAveTemp", headerName: "在预热段时的平均温度", width: 150 },
      { field: "preHtFurPerd", headerName: "预热段在炉时间", width: 150 },
      { field: "ht1SlabTempAve", headerName: "加热段1入口板坯平均温度", width: 150 },
      { field: "ht1SlabHotAve", headerName: "加热段1入口板坯均热度", width: 150 },
      { field: "ht1SlabTempSrfc", headerName: "加热段1入口板坯表面温度", width: 150 },
      { field: "ht1SlabTempCt", headerName: "加热段1入口板坯中心温度", width: 150 },
      { field: "ht1AveTemp", headerName: "在加热段1时的平均温度", width: 150 },
      { field: "ht1InFurPerd", headerName: "加热段1在炉时段", width: 150 },
      { field: "ht2SlabTempAve", headerName: "加热段2入口板坯平均温度", width: 150 },
      { field: "ht2SlabHotAve", headerName: "加热段2入口板坯均热度", width: 150 },
      { field: "ht2SlabTempSrfc", headerName: "加热段2入口板坯表面温度", width: 150 },
      { field: "ht2SlabTempCt", headerName: "加热段2入口板坯中心温度", width: 150 },
      { field: "ht2AveTemp", headerName: "在加热段2时的平均温度", width: 150 },
      { field: "ht2InFurPerd", headerName: "加热段2在炉时段", width: 150 },
      { field: "eqSlabTempAve", headerName: "均热段入口板坯平均温度", width: 150 },
      { field: "eqSlabHotAve", headerName: "均热段入口板坯均热度", width: 150 },
      { field: "eqSlabTempSrfc", headerName: "均热段入口板坯表面温度", width: 150 },
      { field: "eqSlabTempCt", headerName: "均热段入口板坯中心温度", width: 150 },
      { field: "eqAveTemp", headerName: "均热段时的平均温度", width: 150 },
      { field: "eqInFurPerd", headerName: "均热段在炉时段", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 轧制实绩（gridControl10 / TiL2me02Dto） */
  {
    title: "轧制实绩",
    colDefs: [
      { field: "createTime", headerName: "创建时间", width: 150 },
      { field: "plateNo", headerName: "钢板号", width: 150 },
      { field: "slabNo", headerName: "板坯号", width: 150 },
      { field: "planNo", headerName: "计划号", width: 150 },
      { field: "slabStatus", headerName: "BD板坯标识", width: 150 },
      { field: "standNo", headerName: "机架号", width: 150 },
      { field: "steelGrade", headerName: "材质代码", width: 150 },
      { field: "productCode", headerName: "产品代码", width: 150 },
      { field: "dischargeTime", headerName: "出炉时间", width: 150 },
      { field: "rollingTimeStart", headerName: "轧制开始时间", width: 150 },
      { field: "rollingTimeEnd", headerName: "轧制结束时间", width: 150 },
      { field: "crCode", headerName: "CR代码", width: 150 },
      { field: "totalRollingTime", headerName: "总轧制时间s", width: 150 },
      { field: "rmPass", headerName: "粗轧道次", width: 150 },
      { field: "fmPass", headerName: "精轧总轧制道次数", width: 150 },
      { field: "rollingStatus", headerName: "误轧制标记", width: 150 },
      { field: "exitThick", headerName: "轧制厚度（计算）", width: 150 },
      { field: "exitWidth", headerName: "轧制宽度（计算）", width: 150 },
      { field: "exitLength", headerName: "轧制长度（计算）", width: 150 },
      { field: "operateUserCode", headerName: "轧制操作人员代码（改规标记1）", width: 150 },
      { field: "crownMark", headerName: "钢板凸度（实绩标记)", width: 150 },
      { field: "meaThickWs", headerName: "厚度（工作侧）测厚仪", width: 150 },
      { field: "meaThickDs", headerName: "厚度（传动侧）测厚仪", width: 150 },
      { field: "hsbExitTempAvg", headerName: "除鳞后温度（平均）", width: 150 },
      { field: "hsbExitTempMax", headerName: "除鳞后温度（最大）", width: 150 },
      { field: "rmEntTempCal", headerName: "粗轧开轧温度（计算）", width: 150 },
      { field: "rmEntTempAvg", headerName: "粗轧开轧温度（测量平均）", width: 150 },
      { field: "rmEntTempMin", headerName: "粗轧开轧温度（测量最小）", width: 150 },
      { field: "rmEntTempMax", headerName: "粗轧开轧温度（测量最大）", width: 150 },
      { field: "rmEntTempDev", headerName: "粗轧开轧温度（测量偏差）", width: 150 },
      { field: "rmExitTempCal", headerName: "粗轧终轧温度（计算）", width: 150 },
      { field: "rmExitTempAvg", headerName: "粗轧终轧温度（测量平均）", width: 150 },
      { field: "rmExitTempMin", headerName: "粗轧终轧温度（测量最小）", width: 150 },
      { field: "rmExitTempMax", headerName: "粗轧终轧温度（测量最大）", width: 150 },
      { field: "rmExitTempDev", headerName: "粗轧终轧温度（测量偏差）", width: 150 },
      { field: "rmEntThick", headerName: "粗轧开始厚度（计算）", width: 150 },
      { field: "fmEntTempCal", headerName: "精轧开轧温度（计算）", width: 150 },
      { field: "fmEntTempAvg", headerName: "精轧开轧温度（测量平均）", width: 150 },
      { field: "fmEntTempMin", headerName: "精轧开轧温度（测量最小）", width: 150 },
      { field: "fmEntTempMax", headerName: "精轧开轧温度（测量最大）", width: 150 },
      { field: "fmEntTempDev", headerName: "精轧开轧温度（测量偏差）", width: 150 },
      { field: "fmExitTempCal", headerName: "精轧终轧温度（计算）", width: 150 },
      { field: "fmExitTempAvg", headerName: "精轧终轧温度（测量平均）", width: 150 },
      { field: "fmExitTempMin", headerName: "精轧终轧温度（测量最小）", width: 150 },
      { field: "fmExitTempMax", headerName: "精轧终轧温度（测量最大）", width: 150 },
      { field: "fmExitTempDev", headerName: "精轧终轧温度（测量偏差）", width: 150 },
      { field: "fmEntThick", headerName: "精轧开始厚度（计算）", width: 150 },
      { field: "firstConThick", headerName: "第一阶段控制轧制点厚度", width: 150 },
      { field: "secondConThick", headerName: "第二阶段控制轧制点厚度", width: 150 },
      { field: "firstContTemp", headerName: "第一阶段控制轧制点温度", width: 150 },
      { field: "secondConTemp", headerName: "第二阶段控制轧制点温度", width: 150 },
      { field: "thickHp", headerName: "钢板测厚仪中部厚度", width: 150 },
      { field: "broadbef", headerName: "展宽轧制前厚度", width: 150 },
      { field: "broadaft", headerName: "展宽轧制后厚度", width: 150 },
      { field: "shiftNo", headerName: "班次", width: 150 },
      { field: "shiftGroup", headerName: "班组", width: 150 },
      { field: "productTime", headerName: "生产时间", width: 150 },
      { field: "author", headerName: "责任者", width: 150 },
      { field: "slabWeight", headerName: "板坯实际重量", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 轧制异常实绩（gridControl11 / TiL2me01） */
  {
    title: "轧制异常实绩",
    colDefs: [
      { field: "createTime", headerName: "创建时间", width: 150 },
      { field: "plateNo", headerName: "钢板号", width: 150 },
      { field: "slabNo", headerName: "板坯号", width: 150 },
      { field: "zone", headerName: "位置", width: 150 },
      { field: "reason", headerName: "异常原因", width: 150 },
      { field: "actPassNo", headerName: "当前实际道次号", width: 150 },
      { field: "actThick", headerName: "当前厚度", width: 150 },
      { field: "actWidth", headerName: "当前宽度", width: 150 },
      { field: "actLength", headerName: "当前长度", width: 150 },
      { field: "shiftNo", headerName: "班次", width: 150 },
      { field: "shiftGroup", headerName: "班组", width: 150 },
      { field: "productTime", headerName: "生产时间", width: 150 },
      { field: "author", headerName: "责任者", width: 150 },
      { field: "slabWeight", headerName: "板坯实际重量", width: 150 },
      { field: "discAuthor", headerName: "责任者", width: 150 },
      { field: "fmAuthorA", headerName: "精轧责任者A", width: 150 },
      { field: "fmAuthorB", headerName: "精轧责任者B", width: 150 },
      { field: "rmAuthorA", headerName: "粗轧责任者A", width: 150 },
      { field: "rmAuthorB", headerName: "粗轧责任者B", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 预矫直实绩（gridControl7 / TiL2me08） */
  {
    title: "预矫直实绩",
    colDefs: [
      { field: "createTime", headerName: "创建时间", width: 150 },
      { field: "slabNo", headerName: "板坯号", width: 150 },
      { field: "totalPass", headerName: "矫直总次数", width: 150 },
      { field: "currPass", headerName: "矫直当前次数", width: 150 },
      { field: "entryTime", headerName: "进入时间", width: 150 },
      { field: "endTime", headerName: "结束时间", width: 150 },
      { field: "entryTemp", headerName: "钢板温度", width: 150 },
      { field: "levelerSpeed", headerName: "矫直速度", width: 150 },
      { field: "bitSpeed", headerName: "咬入速度", width: 150 },
      { field: "entryGap", headerName: "入口辊缝", width: 150 },
      { field: "exitGap", headerName: "出口辊缝", width: 150 },
      { field: "entrySideRollGap", headerName: "入口边辊高度", width: 150 },
      { field: "exitSideRollGap", headerName: "出口边辊高度", width: 150 },
      { field: "tilt1", headerName: "倾斜量", width: 150 },
      { field: "tilt2", headerName: "倾动量", width: 150 },
      { field: "l2Force", headerName: "矫直力", width: 150 },
      { field: "bendPosition", headerName: "弯辊量", width: 150 },
      { field: "torqueMotor", headerName: "扭矩", width: 150 },
      { field: "emptyFlag", headerName: "是否空过", width: 150 },
      { field: "spare", headerName: "预留", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* ACC超快冷实绩（gridControl9 / TiL2me14） */
  {
    title: "ACC超快冷实绩",
    colDefs: [
      { field: "dHandle", headerName: "处理时间", width: 150 },
      { field: "nStatus", headerName: "处理结果", width: 150 },
      { field: "slabNo", headerName: "板坯号", width: 150 },
      { field: "steelGrade", headerName: "钢种", width: 150 },
      { field: "thick", headerName: "厚度", width: 150 },
      { field: "width", headerName: "宽度", width: 150 },
      { field: "length", headerName: "长度", width: 150 },
      { field: "coolMode", headerName: "冷却模式", width: 150 },
      { field: "startCoolTime", headerName: "开冷时间", width: 150 },
      { field: "finishCoolTime", headerName: "终冷时间", width: 150 },
      { field: "rollAveTemp", headerName: "轧后平均温度", width: 150 },
      { field: "rollMaxTemp", headerName: "轧后温度最大值", width: 150 },
      { field: "rollMinTemp", headerName: "轧后温度最小值", width: 150 },
      { field: "entryAveTemp", headerName: "开冷平均温度", width: 150 },
      { field: "entryMaxTemp", headerName: "开冷最大温度", width: 150 },
      { field: "entryMinTemp", headerName: "开冷最小温度", width: 150 },
      { field: "targetFinishTemp", headerName: "目标返红温度", width: 150 },
      { field: "finishAveTemp", headerName: "返红平均温度", width: 150 },
      { field: "finishMaxTemp", headerName: "返红温度最大", width: 150 },
      { field: "finishMinTemp", headerName: "返红温度最小", width: 150 },
      { field: "scanAveTemp", headerName: "扫描高温计平均温度", width: 150 },
      { field: "scanMaxTemp", headerName: "扫描高温计最大温度", width: 150 },
      { field: "scanMinTemp", headerName: "扫描高温计最小温度", width: 150 },
      { field: "coolingRate", headerName: "实际冷速", width: 150 },
      { field: "fluxA", headerName: "A区设定流量", width: 150 },
      { field: "fluxB", headerName: "B区设定流量", width: 150 },
      { field: "actFluxA", headerName: "A区实际流量", width: 150 },
      { field: "actFluxB", headerName: "B区实际流量", width: 150 },
      { field: "ratioA", headerName: "A区设定水比", width: 150 },
      { field: "ratioB", headerName: "B区设定水比", width: 150 },
      { field: "actRatioA", headerName: "A区实际水比", width: 150 },
      { field: "actRatioB", headerName: "B区实际水比", width: 150 },
      { field: "speed", headerName: "设定辊速", width: 150 },
      { field: "actSpeed", headerName: "实际辊速", width: 150 },
      { field: "aspd", headerName: "设定加速度", width: 150 },
      { field: "actAspd", headerName: "实际加速度", width: 150 },
      { field: "num", headerName: "开启集管组数", width: 150 },
      { field: "uppipeFlow", headerName: "1-28集管上流量", width: 150 },
      { field: "botpipeFlow", headerName: "1-28集管下流量", width: 150 },
      { field: "sideCavityFlow1", headerName: "1-10边腔流量", width: 150 },
      { field: "sideSpary", headerName: "侧喷", width: 150 },
      { field: "midSpary", headerName: "中喷", width: 150 },
      { field: "htsis", headerName: "头尾遮蔽投入信号", width: 150 },
      { field: "headUpLength", headerName: "头上长度", width: 150 },
      { field: "headBotLength", headerName: "头下长度", width: 150 },
      { field: "headUpCoef", headerName: "头上系数", width: 150 },
      { field: "headBotCoef", headerName: "头下系数", width: 150 },
      { field: "tailUpLength", headerName: "尾上长度", width: 150 },
      { field: "tailBotLength", headerName: "尾下长度", width: 150 },
      { field: "tailUpCoef", headerName: "尾上系数", width: 150 },
      { field: "tailBotCoef", headerName: "尾下系数", width: 150 },
      { field: "prh", headerName: "压辊高度A1-10prh", width: 150 },
      { field: "elpbcd", headerName: "电降平台bcd", width: 150 },
      { field: "tempWater", headerName: "水温", width: 150 },
      { field: "pressWater", headerName: "水压", width: 150 },
      { field: "iSpare", headerName: "备用", width: 150 },
      { field: "fSpare", headerName: "备用", width: 150 },
      { field: "total_flow", headerName: "总水量", width: 150 },
      { field: "finishTemp", headerName: "反红温度曲线", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "createTime", headerName: "创建时间", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 热矫直实绩（gridControl8 / TiL2me09） */
  {
    title: "热矫直实绩",
    colDefs: [
      { field: "lastModifier", headerName: "最后修改人", width: 150 },
      { field: "slabNo", headerName: "板坯号", width: 150 },
      { field: "totalPass", headerName: "矫直总次数", width: 150 },
      { field: "currPass", headerName: "矫直当前次数", width: 150 },
      { field: "entryTime", headerName: "进入时间", width: 150 },
      { field: "endTime", headerName: "结束时间", width: 150 },
      { field: "entryTemp", headerName: "钢板温度", width: 150 },
      { field: "levelerSpeed", headerName: "矫直速度", width: 150 },
      { field: "bitSpeed", headerName: "咬入速度", width: 150 },
      { field: "entryGap", headerName: "入口辊缝", width: 150 },
      { field: "exitGap", headerName: "出口辊缝", width: 150 },
      { field: "entrySideRollGap", headerName: "入口边辊高度", width: 150 },
      { field: "exitSideRollGap", headerName: "出口边辊高度", width: 150 },
      { field: "tilt1", headerName: "倾斜量", width: 150 },
      { field: "tilt2", headerName: "倾动量", width: 150 },
      { field: "l2Force", headerName: "矫直力", width: 150 },
      { field: "bendPosition", headerName: "弯辊量", width: 150 },
      { field: "torqueMotor", headerName: "扭矩", width: 150 },
      { field: "emptyFlag", headerName: "是否空过", width: 150 },
      { field: "spare", headerName: "预留", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "createTime", headerName: "创建时间", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 切头剪CS实绩（gridControl12 / TiP48j01） */
  {
    title: "切头剪CS实绩",
    colDefs: [
      { field: "createTime", headerName: "创建时间", width: 150 },
      { field: "inPlateNo", headerName: "入口钢板号", width: 150 },
      { field: "tPlateId", headerName: "头侧板号", width: 150 },
      { field: "bestSurface", headerName: "好面朝向", width: 150 },
      { field: "csTemp", headerName: "剪切温度", width: 150 },
      { field: "operatorId", headerName: "操作者", width: 150 },
      { field: "csTime", headerName: "CS剪切时间", width: 150 },
      { field: "tPlateThk", headerName: "头侧板厚度", width: 150 },
      { field: "tPlateWth", headerName: "头侧板宽度", width: 150 },
      { field: "tPlateLth", headerName: "头侧板长度", width: 150 },
      { field: "tPlateWgt", headerName: "头侧板重量", width: 150 },
      { field: "tOrdNum", headerName: "头侧合同数", width: 150 },
      { field: "tPartMark", headerName: "头侧取板记号", width: 150 },
      { field: "tProductSum", headerName: "头侧成品板总数", width: 150 },
      { field: "tTdsLth", headerName: "头侧剪切长度(头部)", width: 150 },
      { field: "tBdsLth", headerName: "头侧剪切长度(尾部)", width: 150 },
      { field: "tLthMark", headerName: "头侧是否余长标记", width: 150 },
      { field: "bPlateId", headerName: "尾侧板号", width: 150 },
      { field: "bPlateThk", headerName: "尾侧板厚度", width: 150 },
      { field: "bPlateWth", headerName: "尾侧板宽度", width: 150 },
      { field: "bPlateLth", headerName: "尾侧板长度", width: 150 },
      { field: "bPlateWgt", headerName: "尾侧板重量", width: 150 },
      { field: "bOrdNum", headerName: "尾侧合同数", width: 150 },
      { field: "bPartMark", headerName: "尾侧取板记号", width: 150 },
      { field: "bProductSum", headerName: "尾侧成品板总数", width: 150 },
      { field: "bLthMark", headerName: "尾侧是否余长标记", width: 150 },
      { field: "reserved1", headerName: "预留1", width: 150 },
      { field: "reserved2", headerName: "预留2", width: 150 },
      { field: "shiftNo", headerName: "班次", width: 150 },
      { field: "shiftGroup", headerName: "班组", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 双边剪DSS实绩（gridControl13 / TiP48j02） */
  {
    title: "双边剪DSS实绩",
    colDefs: [
      { field: "createTime", headerName: "创建时间", width: 150 },
      { field: "inPlateNo", headerName: "入口钢板号", width: 150 },
      { field: "slCode", headerName: "剪切线代码", width: 150 },
      { field: "dssTemp", headerName: "剪切温度", width: 150 },
      { field: "operatorId", headerName: "操作者", width: 150 },
      { field: "dssTime", headerName: "DSS剪切时间", width: 150 },
      { field: "plateId", headerName: "实物钢板号", width: 150 },
      { field: "plateThk", headerName: "钢板厚度", width: 150 },
      { field: "plateWth", headerName: "钢板宽度", width: 150 },
      { field: "plateLth", headerName: "钢板长度", width: 150 },
      { field: "plateWgt", headerName: "钢板重量", width: 150 },
      { field: "shiftNo", headerName: "班次", width: 150 },
      { field: "shiftGroup", headerName: "班组", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 定尺剪实绩（gridControl14 / TiP48j031） */
  {
    title: "定尺剪实绩",
    colDefs: [
      { field: "inPlateNo", headerName: "入口钢板号", width: 150 },
      { field: "tPlateNo", headerName: "头侧板号", width: 150 },
      { field: "bestSurface", headerName: "好面朝向", width: 150 },
      { field: "dsTemp", headerName: "剪切温度", width: 150 },
      { field: "operatorId", headerName: "操作者", width: 150 },
      { field: "slCode", headerName: "剪切线代码", width: 150 },
      { field: "dsTime", headerName: "CS剪切时间", width: 150 },
      { field: "tPlateThk", headerName: "头侧板厚度", width: 150 },
      { field: "tPlateWth", headerName: "头侧板宽度", width: 150 },
      { field: "tPlateLth", headerName: "头侧板长度", width: 150 },
      { field: "tPlateWgt", headerName: "头侧板重量", width: 150 },
      { field: "tOrdNum", headerName: "头侧合同数", width: 150 },
      { field: "tPartMark", headerName: "头侧取板记号", width: 150 },
      { field: "tProductSum", headerName: "头侧成品板总数", width: 150 },
      { field: "tTdsLth", headerName: "头侧剪切长度(头部)", width: 150 },
      { field: "tBdsLth", headerName: "头侧剪切长度(尾部)", width: 150 },
      { field: "tLthMark", headerName: "头侧是否余长标记", width: 150 },
      { field: "bPlateNo", headerName: "尾侧板号", width: 150 },
      { field: "bPlateThk", headerName: "尾侧板厚度", width: 150 },
      { field: "bPlateWth", headerName: "尾侧板宽度", width: 150 },
      { field: "bPlateLth", headerName: "尾侧板长度", width: 150 },
      { field: "bPlateWgt", headerName: "尾侧板重量", width: 150 },
      { field: "bOrdNum", headerName: "尾侧合同数", width: 150 },
      { field: "bPartMark", headerName: "尾侧取板记号", width: 150 },
      { field: "bProductSum", headerName: "尾侧成品板总数", width: 150 },
      { field: "bLthMark", headerName: "尾侧是否余长标记", width: 150 },
      { field: "reserved0", headerName: "头侧板成品毛长", width: 150 },
      { field: "reserved1", headerName: "切边标记（2两切4四切）", width: 150 },
      { field: "reserved2", headerName: "喷印完成标记", width: 150 },
      { field: "reserved3", headerName: "预留3", width: 150 },
      { field: "cropCutLenTop", headerName: "CROP", width: 150 },
      { field: "cropCutLenBottom", headerName: "CROP", width: 150 },
      { field: "shiftNo", headerName: "班次", width: 150 },
      { field: "shiftGroup", headerName: "班组", width: 150 },
      { field: "actMaxWth", headerName: "头侧宽度最大值（仪表)", width: 150 },
      { field: "actMinWth", headerName: "头侧宽度最小值（仪表)", width: 150 },
      { field: "actAveWth", headerName: "头侧宽度最平均值（仪表)", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "createTime", headerName: "创建时间", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "dHandle", headerName: "处理时间", width: 150, hide: true },
      { field: "nStatus", headerName: "处理结果", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 取大样实绩（gridControl15 / TiP48j04） */
  {
    title: "取大样实绩",
    colDefs: [
      { field: "createTime", headerName: "创建时间", width: 150 },
      { field: "plateNo", headerName: "钢板号", width: 150 },
      { field: "operatorId", headerName: "操作者", width: 150 },
      { field: "bestSurface", headerName: "好面朝向", width: 150 },
      { field: "sampleTime", headerName: "取样时间", width: 150 },
      { field: "samplePos", headerName: "取样位置", width: 150 },
      { field: "sampleLth", headerName: "取样长度", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 超声波探伤UST实绩（gridControl16 / TiP48j05） */
  {
    title: "超声波探伤UST实绩",
    colDefs: [
      { field: "createTime", headerName: "创建时间", width: 150 },
      { field: "plateNo", headerName: "实物钢板号", width: 150 },
      { field: "bestSurface", headerName: "好面朝向", width: 150 },
      { field: "checkEmp", headerName: "检查人员", width: 150 },
      { field: "signEmp", headerName: "签发人员", width: 150 },
      { field: "empId", headerName: "UST责任者", width: 150 },
      { field: "ustDt", headerName: "UST测定时间", width: 150 },
      { field: "ustResult", headerName: "UST结果", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 照核实绩（gridControl17 / TiL2me15） */
  {
    title: "照核实绩",
    colDefs: [
      { field: "slabno", headerName: "板坯号", width: 150 },
      { field: "ocrslabno", headerName: "原始照核板坯号", width: 150 },
      { field: "l2slabno", headerName: "L2请求板坯号", width: 150 },
      { field: "reason", headerName: "原因", width: 150 },
      { field: "reviser", headerName: "修改人", width: 150 },
      { field: "time", headerName: "修改时间", width: 150 },
      { field: "spare1", headerName: "预留", width: 150 },
      { field: "spare2", headerName: "预留", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "createTime", headerName: "创建时间", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 测厚仪测量曲线1（gridControl18 / TiL2me16） */
  {
    title: "测厚仪测量曲线1",
    colDefs: [
      { field: "plateno", headerName: "钢板号", width: 150 },
      { field: "slabno", headerName: "板坯号", width: 150 },
      { field: "planno", headerName: "计划号", width: 150 },
      { field: "wedge", headerName: "楔形", width: 150 },
      { field: "centerthickness", headerName: "中心线厚度曲线", width: 150 },
      { field: "width", headerName: "宽度曲线", width: 150 },
      { field: "spare1", headerName: "预留1", width: 150 },
      { field: "spare2", headerName: "预留2", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "createTime", headerName: "创建时间", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 测厚仪测量曲线2（gridControl19 / TiL2me17） */
  {
    title: "测厚仪测量曲线2",
    colDefs: [
      { field: "plateno", headerName: "钢板号", width: 150 },
      { field: "slabno", headerName: "板坯号", width: 150 },
      { field: "planno", headerName: "计划号", width: 150 },
      { field: "osthickness", headerName: "操作侧厚度曲线", width: 150 },
      { field: "dsthickness", headerName: "传动侧厚度曲线", width: 150 },
      { field: "spare1", headerName: "预留1", width: 150 },
      { field: "spare2", headerName: "预留2", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "createTime", headerName: "创建时间", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 平直度仪测量实绩（gridControl20 / TiL2me18Dto） */
  {
    title: "平直度仪测量实绩",
    colDefs: [
      { field: "slabNo", headerName: "板坯号", width: 150 },
      { field: "hSBheadAveWidth", headerName: "HSB测宽头部平均宽度(冷态)", width: 150 },
      { field: "hSBbodyAveWidth", headerName: "HSB测宽中部平均宽度(冷态)", width: 150 },
      { field: "hSBtailAveWidth", headerName: "HSB测宽尾部平均宽度(冷态)", width: 150 },
      { field: "hSBaveWidth", headerName: "HSB测宽全长平均宽度(冷态)", width: 150 },
      { field: "rMheadAveWidth", headerName: "RM测宽头部平均宽度(冷态)", width: 150 },
      { field: "rMbodyAveWidth", headerName: "RM测宽中部平均宽度(冷态)", width: 150 },
      { field: "rMtailAveWidth", headerName: "RM测宽尾部平均宽度(冷态)", width: 150 },
      { field: "rMaveWidth", headerName: "RM测宽全长平均宽度(冷态)", width: 150 },
      { field: "rSLTmaxWidth", headerName: "平直度仪最大宽度(冷态)", width: 150 },
      { field: "rSLTminWidth", headerName: "平直度仪最小宽度(冷态)", width: 150 },
      { field: "rSLTavewidth", headerName: "平直度仪平均宽度(冷态)", width: 150 },
      { field: "spare1", headerName: "预留", width: 150, hide: true },
      { field: "spare2", headerName: "预留", width: 150, hide: true },
    ],
  },
  /* 终轧温度曲线实绩（gridControl21 / TiL2me19） */
  {
    title: "终轧温度曲线实绩",
    colDefs: [
      { field: "plateno", headerName: "钢板号", width: 150 },
      { field: "slabno", headerName: "板坯号", width: 150 },
      { field: "planno", headerName: "计划号", width: 150 },
      { field: "finishtemp", headerName: "终轧温度曲线", width: 150 },
      { field: "spare1", headerName: "预留1", width: 150 },
      { field: "spare2", headerName: "预留2", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "createTime", headerName: "创建时间", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 能耗实绩（gridControl22 / TiL2me12） */
  {
    title: "能耗实绩",
    colDefs: [
      { field: "time", headerName: "发送时刻", width: 150 },
      { field: "shift", headerName: "班次", width: 150 },
      { field: "turn", headerName: "班组", width: 150 },
      { field: "n2Flow1", headerName: "氮气流量1", width: 150 },
      { field: "n2Pressure1", headerName: "氮气压力1", width: 150 },
      { field: "n2Consumption1", headerName: "氮气累计消耗1", width: 150 },
      { field: "gasFlow1", headerName: "煤气流量1", width: 150 },
      { field: "gasPressure1", headerName: "煤气压力1", width: 150 },
      { field: "gasConsumption1", headerName: "煤气累计消耗1", width: 150 },
      { field: "steamFlow1", headerName: "蒸汽流量1", width: 150 },
      { field: "steamPressure1", headerName: "蒸汽压力1", width: 150 },
      { field: "steamConsumption1", headerName: "蒸汽累计消耗1", width: 150 },
      { field: "n2Flow2", headerName: "氮气流量2", width: 150 },
      { field: "n2Pressure2", headerName: "氮气压力2", width: 150 },
      { field: "n2Consumption2", headerName: "氮气累计消耗2", width: 150 },
      { field: "gasFlow2", headerName: "煤气流量2", width: 150 },
      { field: "gasPressure2", headerName: "煤气压力2", width: 150 },
      { field: "gasConsumption2", headerName: "煤气累计消耗2", width: 150 },
      { field: "steamFlow2", headerName: "蒸汽流量2", width: 150 },
      { field: "steamPressure2", headerName: "蒸汽压力2", width: 150 },
      { field: "steamConsumption2", headerName: "蒸汽累计消耗2", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "createTime", headerName: "创建时间", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "spare1", headerName: "预留1", width: 150, hide: true },
      { field: "spare2", headerName: "预留2", width: 150, hide: true },
      { field: "spare3", headerName: "预留3", width: 150, hide: true },
      { field: "spare4", headerName: "预留4", width: 150, hide: true },
      { field: "spare5", headerName: "预留5", width: 150, hide: true },
      { field: "spare6", headerName: "预留6", width: 150, hide: true },
      { field: "spare7", headerName: "预留7", width: 150, hide: true },
      { field: "spare8", headerName: "预留8", width: 150, hide: true },
      { field: "spare9", headerName: "预留9", width: 150, hide: true },
      { field: "spare10", headerName: "预留10", width: 150, hide: true },
      { field: "spare11", headerName: "预留11", width: 150, hide: true },
      { field: "spare12", headerName: "预留12", width: 150, hide: true },
      { field: "spare13", headerName: "预留13", width: 150, hide: true },
      { field: "spare14", headerName: "预留14", width: 150, hide: true },
      { field: "spare15", headerName: "预留15", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 剪切PDI请求（gridControl23 / TiP48j06） */
  {
    title: "剪切PDI请求",
    colDefs: [
      { field: "plateNo", headerName: "钢板号", width: 150 },
      { field: "posNo", headerName: "请求位置", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "createTime", headerName: "创建时间", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 钢板下线请求（gridControl24 / TiP48j07） */
  {
    title: "钢板下线请求",
    colDefs: [
      { field: "plateNo", headerName: "钢板号", width: 150 },
      { field: "posCode", headerName: "下线点", width: 150 },
      { field: "unloadRsn", headerName: "下线原因", width: 150 },
      { field: "unloadPos", headerName: "下线位置", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "createTime", headerName: "创建时间", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 轮廓仪测量实绩（gridControl25 / TiP48j09） */
  {
    title: "轮廓仪测量实绩",
    colDefs: [
      { field: "plateNo", headerName: "钢板号", width: 150 },
      { field: "subId", headerName: "批号", width: 150 },
      { field: "plateLen", headerName: "钢板长度", width: 150 },
      { field: "headCutLen", headerName: "板头", width: 150 },
      { field: "tailCutLen", headerName: "板尾", width: 150 },
      { field: "errorCode", headerName: "异常代码", width: 150 },
      { field: "opBend", headerName: "OP侧镰刀弯量", width: 150 },
      { field: "drBend", headerName: "DR侧镰刀弯量", width: 150 },
      { field: "opBendindex", headerName: "OP侧镰刀弯量坐标", width: 150 },
      { field: "drBendindex", headerName: "DR侧镰刀弯量坐标", width: 150 },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "createTime", headerName: "创建时间", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
  /* 剪切实绩（gridControl2 / Thr4000Dto） */
  {
    title: "剪切实绩",
    colDefs: [
      { field: "cOrderNo", headerName: "订单号", width: 150 },
      { field: "cBatchNo", headerName: "批号", width: 150 },
      { field: "cStove", headerName: "炉号", width: 150 },
      { field: "cPieceNo", headerName: "头侧件次号", width: 150 },
      { field: "cSgCode", headerName: "钢种", width: 150 },
      { field: "cSgStd", headerName: "执行标准", width: 150 },
      { field: "cSpec", headerName: "规格", width: 150 },
      { field: "nThick", headerName: "坯厚", width: 150 },
      { field: "nWidth", headerName: "坯宽", width: 150 },
      { field: "nLen", headerName: "坯长", width: 150 },
      { field: "nQua", headerName: "支数", width: 150 },
      { field: "nWgt", headerName: "坯重", width: 150 },
      { field: "cTrimFlag", headerName: "切边方式", width: 150 },
      { field: "cInboundNo", headerName: "入库标识", width: 150 },
      { field: "cSlCode", headerName: "剪切线代码", width: 150 },
      { field: "printCount", headerName: "打印次数", width: 150, hide: true },
      { field: "lastPrintTime", headerName: "最后打印时间", width: 150, hide: true },
      { field: "lastPrintUser", headerName: "最后打印人", width: 150, hide: true },
      { field: "id", headerName: "主键", width: 150, hide: true },
      { field: "creator", headerName: "创建人", width: 150, hide: true },
      { field: "createTime", headerName: "创建时间", width: 150, hide: true },
      { field: "lastModifier", headerName: "最后修改人", width: 150, hide: true },
      { field: "lastModifyTime", headerName: "最后修改时间", width: 150, hide: true },
      { field: "cPlanId", headerName: "计划ID", width: 150, hide: true },
      { field: "cZpId", headerName: "thr3000主键", width: 150, hide: true },
      { field: "cMxId", headerName: "THR3010主键", width: 150, hide: true },
      { field: "cLineCode", headerName: "产线", width: 150, hide: true },
      { field: "cMatCode", headerName: "物料编码", width: 150, hide: true },
      { field: "cMatName", headerName: "物料名称", width: 150, hide: true },
      { field: "cLengthType", headerName: "长度类型", width: 150, hide: true },
      { field: "nLenMin", headerName: "长度下限", width: 150, hide: true },
      { field: "nLenMax", headerName: "长度上限", width: 150, hide: true },
      { field: "cEngMinThick", headerName: "厚度下偏差", width: 150, hide: true },
      { field: "cEngMaxThick", headerName: "厚度上偏差", width: 150, hide: true },
      { field: "cEngMinWidth", headerName: "宽度下偏差", width: 150, hide: true },
      { field: "cEngMaxWidth", headerName: "宽度上偏差", width: 150, hide: true },
      { field: "cEngMinLen", headerName: "长度下偏差", width: 150, hide: true },
      { field: "cEngMaxLen", headerName: "长度上偏差", width: 150, hide: true },
      { field: "cCustCode", headerName: "客户编码", width: 150, hide: true },
      { field: "cCustName", headerName: "客户名称", width: 150, hide: true },
      { field: "dDeliveryDate", headerName: "交货日期", width: 150, hide: true },
      { field: "dOrdDate", headerName: "订单日期", width: 150, hide: true },
      { field: "cSpecReqText", headerName: "客户特殊要求", width: 150, hide: true },
      { field: "cConNo", headerName: "合同号", width: 150, hide: true },
      { field: "cSteelType", headerName: "钢种大类", width: 150, hide: true },
      { field: "cDelivyStatusCode", headerName: "交货状态", width: 150, hide: true },
      { field: "cCustStdCode", headerName: "加工用途代码", width: 150, hide: true },
      { field: "cOrderCustCname", headerName: "订货客户中文名称", width: 150, hide: true },
      { field: "cConsigneeCustCname", headerName: "收货客户中文名称", width: 150, hide: true },
      { field: "cPieceNoSlab", headerName: "板坯号", width: 150, hide: true },
      { field: "cSgCodeSlab", headerName: "钢坯钢种", width: 150, hide: true },
      { field: "cSgStdSlab", headerName: "坯料执行标准", width: 150, hide: true },
      { field: "cSpecSlab", headerName: "板坯规格", width: 150, hide: true },
      { field: "nThickSlab", headerName: "坯料厚度", width: 150, hide: true },
      { field: "nWidthSlab", headerName: "坯料宽度", width: 150, hide: true },
      { field: "nLenSlab", headerName: "坯料长度", width: 150, hide: true },
      { field: "nQuaSlab", headerName: "钢坯总支数", width: 150, hide: true },
      { field: "nWgtSlab", headerName: "坯重", width: 150, hide: true },
      { field: "cMatCodeSlab", headerName: "坯料物料编码", width: 150, hide: true },
      { field: "cMatNameSlab", headerName: "坯料物料名称", width: 150, hide: true },
      { field: "nFurType", headerName: "装炉方式", width: 150, hide: true },
      { field: "cFurCode", headerName: "加热炉编号", width: 150, hide: true },
      { field: "cRollCode", headerName: "轧机编号", width: 150, hide: true },
      { field: "dFinish", headerName: "完成时间", width: 150, hide: true },
      { field: "cFinishShift", headerName: "完成班次", width: 150, hide: true },
      { field: "cFinishGroup", headerName: "完成班组", width: 150, hide: true },
      { field: "cFinishEmp", headerName: "轧制完成人", width: 150, hide: true },
      { field: "cConfirmStatus", headerName: "确认判定状态", width: 150, hide: true },
      { field: "cConfirmShift", headerName: "收料班次", width: 150, hide: true },
      { field: "cConfirmGroup", headerName: "收料班组", width: 150, hide: true },
      { field: "cConfirmEmp", headerName: "收料人", width: 150, hide: true },
      { field: "dConfirm", headerName: "收料时间", width: 150, hide: true },
      { field: "cSurfaceResult", headerName: "表检结果", width: 150, hide: true },
      { field: "dSurfaceTime", headerName: "表面判定时间", width: 150, hide: true },
      { field: "cSurfaceUser", headerName: "表面判定人", width: 150, hide: true },
      { field: "cSurfaceRemark", headerName: "缺陷描述", width: 150, hide: true },
      { field: "cRespDept", headerName: "责任部门", width: 150, hide: true },
      { field: "cFaceHandleAdvice", headerName: "处置措施", width: 150, hide: true },
      { field: "cSampleLotNo", headerName: "试批号", width: 150, hide: true },
      { field: "cSampleLotNoSlab", headerName: "坯料试批号", width: 150, hide: true },
      { field: "cQmHandleDesc", headerName: "处置注释", width: 150, hide: true },
      { field: "nStatus", headerName: "处理标记", width: 150, hide: true },
      { field: "cStoreCode", headerName: "库区号", width: 150, hide: true },
      { field: "cStackNo", headerName: "垛位号", width: 150, hide: true },
      { field: "cStackNum", headerName: "层号", width: 150, hide: true },
      { field: "cFlawDesc", headerName: "探伤等级", width: 150, hide: true },
      { field: "cDelivyAddress", headerName: "流向", width: 150, hide: true },
      { field: "cProdCode", headerName: "品名", width: 150, hide: true },
      { field: "cWgtToler", headerName: "重量偏差等级", width: 150, hide: true },
      { field: "nOrderThick", headerName: "订货厚", width: 150, hide: true },
      { field: "nOrderWidth", headerName: "订货宽", width: 150, hide: true },
      { field: "cOrderLenType", headerName: "合同长度类型", width: 150, hide: true },
      { field: "nOrderLenMax", headerName: "订单长2", width: 150, hide: true },
      { field: "nOrderLenMin", headerName: "订单长", width: 150, hide: true },
      { field: "nOrderLen", headerName: "订货长mm", width: 150, hide: true },
      { field: "nCalWgt", headerName: "理重", width: 150, hide: true },
      { field: "cPrint", headerName: "喷印完成标记", width: 150, hide: true },
      { field: "dPrint", headerName: "喷印完成时间", width: 150, hide: true },
      { field: "nLenSj", headerName: "实际长度", width: 150, hide: true },
      { field: "nThickSj", headerName: "成品厚度", width: 150, hide: true },
      { field: "nWidthSj", headerName: "成品宽度", width: 150, hide: true },
      { field: "cPlateNo", headerName: "大板号", width: 150, hide: true },
      { field: "nProType", headerName: "库存类型", width: 150, hide: true },
      { field: "selected", headerName: "选择", width: 150, hide: true },
    ],
  },
];
